apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: todo-app
spec:
  type: {{ .Values.service.type }} # We set this to LoadBalancer in values.yaml
  ports:
    - port: {{ .Values.service.port }}       # Port exposed to internet (80)
      targetPort: 3000                       # Port app listens on (Matches Deployment)
      protocol: TCP
      name: http
  selector:
    app: todo-app # This must match the labels in deployment.yaml