# --- ADD THIS (Required by your Ingress template) ---
appName: todo-app
# ----------------------------------------------------

replicaCount: 1
image:
  repository: potdartapan/todo-app
  pullPolicy: Always
  tag: "b2ef54e5eeff6bc7f8152f5b4e0e32f1fc1f3f18"
service:
  # CHANGE THIS: Use ClusterIP because Nginx Ingress handles external access
  type: ClusterIP
  port: 80
  targetPort: 3000
