# --- ADD THIS (Required by your Ingress template) ---
appName: todo-app
# ----------------------------------------------------

replicaCount: 1
image:
  repository: potdartapan/todo-app
  pullPolicy: Always
  tag: "4c9bd9d7f59424a262b28b0323d551cbfad8a918"
service:
  # CHANGE THIS: Use ClusterIP because Nginx Ingress handles external access
  type: ClusterIP
  port: 80
  targetPort: 3000
