appName: "todo-app"
replicaCount: 1
image:
  repository: potdartapan/todo-app # Your DockerHub Username
  pullPolicy: Always
  tag: "eabc896dcb92025fffdcd921f0affaad683ce01e" # Will be overridden by GitHub Actions
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
