replicaCount: 1
image:
  repository: potdartapan/todo-app # Your DockerHub Username
  pullPolicy: Always
  tag: "c6fa7d6dffe68f549aae41d96faf2ce198170fee" # Will be overridden by GitHub Actions
service:
  type: LoadBalancer
  port: 80
