replicaCount: 1
image:
  repository: potdartapan/todo-app # Your DockerHub Username
  pullPolicy: Always
  tag: "3f94867e68754a6089c8f9e195b9abc2ae35e175" # Will be overridden by GitHub Actions
service:
  type: LoadBalancer
  port: 80
