name: Application CI (GitOps)

on:
  push:
    branches: [ "master" ]
    paths:
      - 'app/**'        # Only trigger if the python code changes
      - 'app/Dockerfile' # Explicitly include Dockerfile (if it's inside app/)
      - 'app/requirements.txt'
  workflow_dispatch:
jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r app/requirements.txt

      - name: Run Pylint
        run: |
          pylint app/**/*.py --fail-under=7.0 >pylint_report.txt

      - name: Upload Pylint Report
        if: always() # Ensure this runs even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: pylint-report
          path: pylint_report.txt
  trivy-fs-scan:
    runs-on: ubuntu-latest
    needs: pylint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan repo using trivy
        uses: aquasecurity/trivy-action@master
        with: 
          scan-type: 'fs'
          ignore-unfixed: true
          format: table
          output: 'trivy-status.txt'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
      - name: Upload trivy artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-status
          path: trivy-status.txt

  sonarqube:
    runs-on: ubuntu-latest
    needs: trivy-fs-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
          args: >
            -Dsonar.coverage.exclusions=**/*.py

      - name: SonarQube Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-update-git:
    runs-on: ubuntu-latest
    needs: sonarqube
    permissions:
      contents: write # REQUIRED: Allows the Action to push commits to your repo

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 1. Docker Build & Push (Use the Commit SHA as the tag)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          # We push the SHA specific tag
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ github.sha }}

      # 2. Update values.yaml (The "GitOps" Step)
      # We use 'yq' (a lightweight YAML processor) to edit the file safely
      - name: Update Image Tag in Helm
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag = "${{ github.sha }}"' 'k8s/apps/todo-app/values.yaml'

      # 3. Commit and Push the Change back to Repo
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check if there are changes (to avoid empty commit errors)
          if [[ -n $(git status -s) ]]; then
            git add k8s/apps/todo-app/values.yaml
            git commit -m "Update image tag to ${{ github.sha }}"
            git push
          else
            echo "No changes to commit."
          fi